### PR TITLE
Added a SVG icon.

### PR DESCRIPTION
**Pull request by lucaboesch**
I unfortunately couldn't decide whether that should be a zigzag ore a wave form underline…

### CODE REVIEW

**Comment by timhunt** [comment]
They are alkanes, so zig-zag https://en.wikipedia.org/wiki/Alkane#Branched_alkanes

**Comment by lucaboesch** [comment]
Oh great. Are the angles too steep? I can flatten them to resemble https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Pentane-2D-Skeletal.svg/240px-Pentane-2D-Skeletal.svg.png some more.

**Comment by timhunt** [comment]
That would be a good thing to match.

**Comment by lucaboesch** [comment]
There you go, I tried!

**Comment by timhunt** [comment]
Hi Luca. Sorry to be a pain. Two things:

1. I just renamed master branch to main, which means github no longer likes this pull request.
2. Rendered at default size, the image is not a very nice bitmap. I think the zig-zag line needs to be fractionally thicker, and I would look at the exact font, size and position of the brackets.

It is close though.

**Pull request closed without merging**
